### ISSUE TITLE
if steam vr is killed, this plugin crashes obs.

### ISSUE THREAD

**Issue by QTpyeRose** [Pigney/OpenVR-Capture#10]
when running SteamVR, if steam vr is killed or crashes it takes down the entirety of OBS with it, when the plugin is capturing. this also kills any recordings/streams.

**Comment by Pigney** [comment]
can you confirm you're on the latest version 1.8.3? this should have been fixed a while back

**Comment by QTpyeRose** [comment]
yes i am on plugin version 1.8.3, and OBS 31.0.3. i was using an older version, but i updated. and its still happening.

but it specifically only happens in some ways, if steam vr seems to close down "gracefully" it does not seem to crash, but if the vr game or steamvr crashes it can take down obs.

im not sure its internals, but you may need something like a check for if the stream/openvr/api or whatever just suddenly stopped responding and do some error recovery or something. 

i tried finding a log of the crash but i unfonitly dont have one on hand

**Comment by QTpyeRose** [comment]
alright this is very odd. it not happending in my testing right now, if it does happen again ill grab the log and let you know

**Comment by QTpyeRose** [comment]
still happening in 1.8.4 

[2025-05-12 15-08-12.txt](https://github.com/user-attachments/files/20176425/2025-05-12.15-08-12.txt)

(did not generate anything in the crashes folder)

**Comment by Pigney** [comment]
Okay i'll take a look, must have missed something. thanks for telling me :)

**Comment by RayneYoruka** [comment]
I can confirm the same behaviour as mentioned by @QtpyeRose. I was checking my logs and whatnot to confirm it was a crash, same exact behaviour when exiting SteamVR.

**Comment by pudimdecana** [comment]
Hi, I can confirm this problem, but it only happens if OBS is being ran as admin for me, and if the rest of the applications are not.

**Comment by RayneYoruka** [comment]
Interesting.. to me it does happen and I do not run OBS with admin.

**Comment by Pigney** [comment]
May everybody please try the [latest pre-release?](https://github.com/Pigney/OpenVR-Capture/releases/tag/v1.9.0pre)

**Comment by RayneYoruka** [comment]
I've seen the emails about the update and the seeking testers, I'll be testing on the upcoming days once I'm off work.

**Comment by pudimdecana** [comment]
> May everybody please try the [latest pre-release?](https://github.com/Pigney/OpenVR-Capture/releases/tag/v1.9.0pre)

Should we be looking for something specific other than this crash?

Updating rn.

**Comment by pudimdecana** [comment]
Alright, after some sessions of playing/testing

Can confirm that in no situation, killing SteamVR killed OBS.

-Kept closing and opening SteamVR for a few minutes

-Played some games, repeated above

However, there was one time where I closed SteamVR and opened it again, and the plugin wouldn't work, it would not capture OpenVR, I tried disabling and enabling the source again, but nothing. Rebooting OBS fixed it.

**Comment by Pigney** [comment]
> Alright, after some sessions of playing/testing
> 
> Can confirm that in no situation, killing SteamVR killed OBS.
> 
> -Kept closing and opening SteamVR for a few minutes
> 
> -Played some games, repeated above
> 
> However, there was one time where I closed SteamVR and opened it again, and the plugin wouldn't work, it would not capture OpenVR, I tried disabling and enabling the source again, but nothing. Rebooting OBS fixed it.

Much to my dismay this is the way the OpenVR SDK works, it has to fully shutdown to avoid force-quitting OBS which means it cannot re-capture until OBS is restarted. I am very glad to hear the original issue is gone though :)
